<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DisburseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Insert Agents
        DB::table('agents')->insert([
            ['id' => 7, 'name' => 'Salman Khan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'name' => 'Amir Khan', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'name' => 'Pawan Kumar', 'status' => 1, 'created_at' => now(), 'updated_at' => now()],
        ]);

        // 2. Insert Sample Disburse Records
        DB::table('disburse')->insert([
    [
        'disburse_id' => 'DISB-1021',
        'loan_acc' => 'LN-882190',
        'agent_id' => 1,
        'customer_name' => 'Rajesh Singh',
        'contact' => '9876543210',
        'vehicle_model' => 'Maruti Swift',
        'bank_name' => 'Yes Bank',
        'services' => 'New',
        'loan_amount' => 500000.00,
        'total_commission' => 15000.00,
        'agent_commission' => 10000.00,
        'profit' => 5000.00,
        'disburse_date' => '2026-02-10',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1022',
        'loan_acc' => 'LN-882191',
        'agent_id' => 2,
        'customer_name' => 'Suman Gupta',
        'contact' => '9812345678',
        'vehicle_model' => 'Hyundai Creta',
        'bank_name' => 'SBI Bank',
        'services' => 'Used',
        'loan_amount' => 750000.00,
        'total_commission' => 22500.00,
        'agent_commission' => 15000.00,
        'profit' => 7500.00,
        'disburse_date' => '2026-02-15',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1033',
        'loan_acc' => 'LN-882192',
        'agent_id' => 1,
        'customer_name' => 'Vikas Patel',
        'contact' => '9765432109',
        'vehicle_model' => 'Tata Nexon',
        'bank_name' => 'PNB Bank',
        'services' => 'Top-Up',
        'loan_amount' => 300000.00,
        'total_commission' => 9000.00,
        'agent_commission' => 6000.00,
        'profit' => 3000.00,
        'disburse_date' => '2026-02-20',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1004',
        'loan_acc' => 'LN-882193',
        'agent_id' => 3,
        'customer_name' => 'Amitabh Roy',
        'contact' => '9830123456',
        'vehicle_model' => 'Mahindra Thar',
        'bank_name' => 'Yes Bank',
        'services' => 'Purchase',
        'loan_amount' => 1100000.00,
        'total_commission' => 33000.00,
        'agent_commission' => 22000.00,
        'profit' => 11000.00,
        'disburse_date' => '2026-02-21',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1005',
        'loan_acc' => 'LN-882194',
        'agent_id' => 2,
        'customer_name' => 'Pooja Sharma',
        'contact' => '9920112233',
        'vehicle_model' => 'Kia Seltos',
        'bank_name' => 'SBI Bank',
        'services' => 'Refinance',
        'loan_amount' => 650000.00,
        'total_commission' => 19500.00,
        'agent_commission' => 13000.00,
        'profit' => 6500.00,
        'disburse_date' => '2026-02-22',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1006',
        'loan_acc' => 'LN-882195',
        'agent_id' => 1,
        'customer_name' => 'Rohan Mehta',
        'contact' => '9845098765',
        'vehicle_model' => 'Honda City',
        'bank_name' => 'PNB Bank',
        'services' => 'B.T. Top-Up',
        'loan_amount' => 450000.00,
        'total_commission' => 13500.00,
        'agent_commission' => 9000.00,
        'profit' => 4500.00,
        'disburse_date' => '2026-02-23',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1007',
        'loan_acc' => 'LN-882196',
        'agent_id' => 3,
        'customer_name' => 'Sanjay Verma',
        'contact' => '9711223344',
        'vehicle_model' => 'Toyota Fortuner',
        'bank_name' => 'Yes Bank',
        'services' => 'New',
        'loan_amount' => 2500000.00,
        'total_commission' => 75000.00,
        'agent_commission' => 50000.00,
        'profit' => 25000.00,
        'disburse_date' => '2026-02-24',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1008',
        'loan_acc' => 'LN-882197',
        'agent_id' => 2,
        'customer_name' => 'Neha Kapoor',
        'contact' => '9899887766',
        'vehicle_model' => 'Maruti Brezza',
        'bank_name' => 'SBI Bank',
        'services' => 'Used',
        'loan_amount' => 550000.00,
        'total_commission' => 16500.00,
        'agent_commission' => 11000.00,
        'profit' => 5500.00,
        'disburse_date' => '2026-02-25',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1009',
        'loan_acc' => 'LN-882198',
        'agent_id' => 1,
        'customer_name' => 'Karan Malhotra',
        'contact' => '9650123456',
        'vehicle_model' => 'Hyundai Venue',
        'bank_name' => 'PNB Bank',
        'services' => 'Top-Up',
        'loan_amount' => 280000.00,
        'total_commission' => 8400.00,
        'agent_commission' => 5600.00,
        'profit' => 2800.00,
        'disburse_date' => '2026-02-25',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1010',
        'loan_acc' => 'LN-882199',
        'agent_id' => 3,
        'customer_name' => 'Anil Joshi',
        'contact' => '9820011223',
        'vehicle_model' => 'Tata Punch',
        'bank_name' => 'Yes Bank',
        'services' => 'New',
        'loan_amount' => 400000.00,
        'total_commission' => 12000.00,
        'agent_commission' => 8000.00,
        'profit' => 4000.00,
        'disburse_date' => '2026-02-26',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1011',
        'loan_acc' => 'LN-882200',
        'agent_id' => 2,
        'customer_name' => 'Sunita Rao',
        'contact' => '9733445566',
        'vehicle_model' => 'Mahindra XUV700',
        'bank_name' => 'SBI Bank',
        'services' => 'Purchase',
        'loan_amount' => 1400000.00,
        'total_commission' => 42000.00,
        'agent_commission' => 28000.00,
        'profit' => 14000.00,
        'disburse_date' => '2026-02-26',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1012',
        'loan_acc' => 'LN-882201',
        'agent_id' => 1,
        'customer_name' => 'Manoj Tiwari',
        'contact' => '9811223344',
        'vehicle_model' => 'Maruti Dzire',
        'bank_name' => 'PNB Bank',
        'services' => 'Refinance',
        'loan_amount' => 350000.00,
        'total_commission' => 10500.00,
        'agent_commission' => 7000.00,
        'profit' => 3500.00,
        'disburse_date' => '2026-02-27',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1013',
        'loan_acc' => 'LN-882202',
        'agent_id' => 3,
        'customer_name' => 'Deepak Chawla',
        'contact' => '9910223344',
        'vehicle_model' => 'Kia Sonet',
        'bank_name' => 'Yes Bank',
        'services' => 'B.T. Top-Up',
        'loan_amount' => 520000.00,
        'total_commission' => 15600.00,
        'agent_commission' => 10400.00,
        'profit' => 5200.00,
        'disburse_date' => '2026-02-27',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1014',
        'loan_acc' => 'LN-882203',
        'agent_id' => 2,
        'customer_name' => 'Aarti Saxena',
        'contact' => '9871122334',
        'vehicle_model' => 'Honda Elevate',
        'bank_name' => 'SBI Bank',
        'services' => 'New',
        'loan_amount' => 800000.00,
        'total_commission' => 24000.00,
        'agent_commission' => 16000.00,
        'profit' => 8000.00,
        'disburse_date' => '2026-02-27',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1015',
        'loan_acc' => 'LN-882204',
        'agent_id' => 1,
        'customer_name' => 'Gaurav Chaudhary',
        'contact' => '9643001122',
        'vehicle_model' => 'Volkswagen Taigun',
        'bank_name' => 'PNB Bank',
        'services' => 'Used',
        'loan_amount' => 600000.00,
        'total_commission' => 18000.00,
        'agent_commission' => 12000.00,
        'profit' => 6000.00,
        'disburse_date' => '2026-02-28',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1016',
        'loan_acc' => 'LN-882205',
        'agent_id' => 3,
        'customer_name' => 'Kavita Pandey',
        'contact' => '9868112233',
        'vehicle_model' => 'Skoda Kushaq',
        'bank_name' => 'Yes Bank',
        'services' => 'Top-Up',
        'loan_amount' => 320000.00,
        'total_commission' => 9600.00,
        'agent_commission' => 6400.00,
        'profit' => 3200.00,
        'disburse_date' => '2026-02-28',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1017',
        'loan_acc' => 'LN-882206',
        'agent_id' => 2,
        'customer_name' => 'Nitin Bansal',
        'contact' => '9717001122',
        'vehicle_model' => 'MG Hector',
        'bank_name' => 'SBI Bank',
        'services' => 'Purchase',
        'loan_amount' => 1250000.00,
        'total_commission' => 37500.00,
        'agent_commission' => 25000.00,
        'profit' => 12500.00,
        'disburse_date' => '2026-02-28',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1018',
        'loan_acc' => 'LN-882207',
        'agent_id' => 1,
        'customer_name' => 'Pankaj Deshmukh',
        'contact' => '9891002233',
        'vehicle_model' => 'Maruti Baleno',
        'bank_name' => 'PNB Bank',
        'services' => 'Refinance',
        'loan_amount' => 480000.00,
        'total_commission' => 14400.00,
        'agent_commission' => 9600.00,
        'profit' => 4800.00,
        'disburse_date' => '2026-02-28',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1019',
        'loan_acc' => 'LN-882208',
        'agent_id' => 3,
        'customer_name' => 'Shweta Bhatia',
        'contact' => '9810998877',
        'vehicle_model' => 'Renault Triber',
        'bank_name' => 'Yes Bank',
        'services' => 'New',
        'loan_amount' => 380000.00,
        'total_commission' => 11400.00,
        'agent_commission' => 7600.00,
        'profit' => 3800.00,
        'disburse_date' => '2026-02-28',
        'created_at' => now(),
        'updated_at' => now()
    ],
    [
        'disburse_id' => 'DISB-1020',
        'loan_acc' => 'LN-882209',
        'agent_id' => 2,
        'customer_name' => 'Rahul Nambiar',
        'contact' => '9940112233',
        'vehicle_model' => 'Toyota Innova Crysta',
        'bank_name' => 'SBI Bank',
        'services' => 'Used',
        'loan_amount' => 1600000.00,
        'total_commission' => 48000.00,
        'agent_commission' => 32000.00,
        'profit' => 16000.00,
        'disburse_date' => '2026-02-28',
        'created_at' => now(),
        'updated_at' => now()
    ],
]);
    }
}